-- api_keys.id has no sequence in production — "Key storage failed" (2026-08-11)
--
-- WHAT IS WRONG. scripts/supabase_all_tables.sql:232 declares
--
--     id  BIGSERIAL PRIMARY KEY
--
-- but the LIVE table has `id bigint NOT NULL` with `column_default: null`. The
-- table and the file that claims to define it disagree, so every INSERT that
-- omits `id` fails the NOT NULL constraint and the endpoint returns
-- {"detail":"Key storage failed"}.
--
-- The table predates this file, or was created by a different path. Which is the
-- point worth keeping: a CREATE TABLE script is not a schema, it is a script that
-- ran once. `IF NOT EXISTS` guarantees it will never correct a table that already
-- exists and is wrong — it will silently confirm it. The authority is the live
-- catalog, and it has to be asked, not assumed.
--
-- I diagnosed this wrong twice before getting here: first "anon lacks INSERT"
-- (it does not), then "SUPABASE_SERVICE_KEY is missing" (it was not the cause).
-- Both were plausible and neither was checked against information_schema. The
-- fix took one query against the catalog; the two wrong answers took longer.

-- ── VERIFY THE DIAGNOSIS FIRST (do not skip — if this returns a default, stop) ──
-- select column_name, data_type, is_nullable, column_default
--   from information_schema.columns
--  where table_name = 'api_keys' and column_name = 'id';
-- expect: bigint | NO | null      ← null default is the bug

-- ── FIX ────────────────────────────────────────────────────────────────────────
-- Identity rather than a bare sequence: it is owned by the column, so it cannot be
-- orphaned by a later table rewrite, and it is what BIGSERIAL should have produced.
alter table api_keys
  alter column id add generated by default as identity;

-- Start the counter above anything already inserted by hand, so the first
-- generated id cannot collide with an existing row.
select setval(pg_get_serial_sequence('api_keys', 'id'),
              coalesce((select max(id) from api_keys), 0) + 1,
              false);

-- ── CONFIRM ────────────────────────────────────────────────────────────────────
-- select column_name, column_default, is_identity
--   from information_schema.columns
--  where table_name = 'api_keys' and column_name = 'id';
-- expect: is_identity = YES
--
-- Then, end to end (this is the check that actually matters — the catalog looking
-- right is not the same fact as issuance working):
--   curl -s -X POST "$API/api/v1/keys" -H "Content-Type: application/json" \
--     -d '{"name":"smoke","email":"jazz@cometcloud.ai","intended_use":"smoke test"}'
-- expect a key payload, not {"detail":"Key storage failed"}.
--
-- ── AND THEN DELETE THE SMOKE KEY ──────────────────────────────────────────────
-- delete from api_keys where name = 'smoke';
