-- ═══════════════════════════════════════════════════════════════════
-- CometCloud AI — Complete Supabase Schema
-- Run this ONCE in Supabase SQL Editor
-- Dashboard → SQL Editor → New Query → paste → Run
-- URL: https://supabase.com/dashboard/project/soupjamxlfsmgmmtoeok/sql/new
-- ═══════════════════════════════════════════════════════════════════

-- ─── 1. CIS Score History ────────────────────────────────────────────────────
-- Stores every 30-min push from Mac Mini via /internal/cis-scores
CREATE TABLE IF NOT EXISTS cis_scores (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    symbol      TEXT NOT NULL,
    name        TEXT,
    score       REAL,
    grade       TEXT,
    signal      TEXT,
    percentile  REAL,
    pillar_f    REAL,
    pillar_m    REAL,
    pillar_o    REAL,
    pillar_s    REAL,
    pillar_a    REAL,
    asset_class TEXT,
    source      TEXT DEFAULT 'local_engine',
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cis_scores_symbol_time
    ON cis_scores (symbol, recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_cis_scores_class_time
    ON cis_scores (asset_class, recorded_at DESC);

ALTER TABLE cis_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "cis_scores_select" ON cis_scores
    FOR SELECT USING (true);

CREATE POLICY "cis_scores_insert" ON cis_scores
    FOR INSERT WITH CHECK (true);


-- ─── 2. Macro Brief History ───────────────────────────────────────────────────
-- Archives daily macro briefs generated by local LM Studio / Qwen3
CREATE TABLE IF NOT EXISTS macro_briefs (
    id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    brief         TEXT NOT NULL,
    model         TEXT,
    data_snapshot JSONB,
    source        TEXT DEFAULT 'local_engine',
    recorded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_macro_briefs_time
    ON macro_briefs (recorded_at DESC);

ALTER TABLE macro_briefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "macro_briefs_select" ON macro_briefs
    FOR SELECT USING (true);

CREATE POLICY "macro_briefs_insert" ON macro_briefs
    FOR INSERT WITH CHECK (true);


-- ─── 3. Wallet Auth Profiles ──────────────────────────────────────────────────
-- Sign-in-with-Solana (Phantom wallet) nonce + profile store
CREATE TABLE IF NOT EXISTS wallet_profiles (
    wallet_address  TEXT PRIMARY KEY,
    display_name    TEXT,
    nonce           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW(),
    last_seen       TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE wallet_profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "wp_select" ON wallet_profiles
    FOR SELECT TO anon USING (true);

CREATE POLICY "wp_insert" ON wallet_profiles
    FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "wp_update" ON wallet_profiles
    FOR UPDATE TO anon USING (true);


-- ─── 4. Investor Leads ────────────────────────────────────────────────────────
-- Captured from strategy.html contact form
CREATE TABLE IF NOT EXISTS leads (
    id              uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name            text NOT NULL,
    email           text NOT NULL,
    organization    text,
    investment_range text,
    message         text,
    ref             text,
    source_page     text DEFAULT 'strategy',
    status          text DEFAULT 'new',
    created_at      timestamptz DEFAULT now()
);

ALTER TABLE leads ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_leads_ref        ON leads(ref);
CREATE INDEX IF NOT EXISTS idx_leads_created_at ON leads(created_at DESC);


-- ─── 5. Vault Deposit Intents ─────────────────────────────────────────────────
-- Solana memo transaction attribution (BumbleBee / Drift vault)
CREATE TABLE IF NOT EXISTS vault_deposit_intents (
    id             uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    wallet_address text NOT NULL,
    vault_id       text,
    vault_address  text,
    partner        text,
    amount_usdc    numeric,
    tx_signature   text UNIQUE,
    memo_data      jsonb,
    source         text DEFAULT 'cometcloud',
    created_at     timestamptz DEFAULT now()
);

ALTER TABLE vault_deposit_intents ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_vdi_wallet  ON vault_deposit_intents(wallet_address);
CREATE INDEX IF NOT EXISTS idx_vdi_partner ON vault_deposit_intents(partner);


-- ═══════════════════════════════════════════════════════════════════
-- NEXT STEPS after running this:
--   1. Supabase → Settings → API → copy:
--      Project URL  → SUPABASE_URL in Railway
--      anon key     → NOT used for server writes
--      service_role → SUPABASE_KEY in Railway  (Settings → API → Reveal)
--   2. Railway → looloomi-ai → Variables → add:
--      SUPABASE_URL = https://soupjamxlfsmgmmtoeok.supabase.co
--      SUPABASE_KEY = <service_role key>
--   3. Mac Mini scores will auto-persist on next 30-min push cycle
--   4. ScoreAnalytics heatmap + Sector Rotation will populate within 24h
-- ═══════════════════════════════════════════════════════════════════
