"""
CometCloud Agent Scheduler Configuration

Phase G — Agent SDK scheduled tasks
Generates cron.d format for Mac Mini deployment.

Schedule (staggered to avoid simultaneous updates):
  market-signal   : 0  * * * *   (hourly at :00)
  cis-scorer      : 5  * * * *   (hourly at :05)
  macro-pulse     : 10 * * * *   (hourly at :10)
  gp-monitor      : 0  6 * * *   (daily at 06:00)
  report-generator: 0  7 * * *   (daily at 07:00)
"""

import os
from pathlib import Path

# Path to the orchestrator entry point (relative to Mac Mini workspace)
ORCHESTRATOR_PATH = "/Users/sbb/Projects/looloomi-ai/src/agents/orchestrator.py"

# Agent schedule map — cron expression -> agent name
SCHEDULES = {
    "0 * * * *": "market-signal",      # :00 every hour
    "5 * * * *": "cis-scorer",         # :05 every hour
    "10 * * * *": "macro-pulse",       # :10 every hour
    "0 6 * * *": "gp-monitor",         # 06:00 daily
    "0 7 * * *": "report-generator",   # 07:00 daily
}


def generate_cron_entries():
    """Generate crontab entries for all scheduled agents."""
    entries = []
    for cron_expr, agent in SCHEDULES.items():
        # Use absolute path to orchestrator
        entry = f"{cron_expr} cd /Users/sbb/Projects/looloomi-ai && python3 {ORCHESTRATOR_PATH} --agent {agent}"
        entries.append((cron_expr, entry))
    return entries


def print_crontab():
    """Print full crontab format for Mac Mini."""
    print("# CometCloud Agent Scheduler — Phase G")
    print("# Generated by scheduler_config.py")
    print("# Schedule: market-signal(:00) → cis-scorer(:05) → macro-pulse(:10) | gp-monitor(06:00) | report-generator(07:00)")
    print()

    # Environment
    print(f"# Mac Mini environment: /Volumes/CometCloudAI/cometcloud-local/")
    print(f"# Railway endpoint: https://web-production-0cdf76.up.railway.app")
    print()

    # Shebang/control
    print("# m h  dom mon dow   command")
    print()

    for cron_expr, entry in generate_cron_entries():
        print(entry)

    print()
    print("# End CometCloud Agent Scheduler")


def write_crontab_file(path: str = "/tmp/cometcloud_cron"):
    """Write crontab to a file for review before deployment."""
    with open(path, "w") as f:
        f.write("# CometCloud Agent Scheduler — Phase G\n")
        f.write("# Schedule: market-signal(:00) → cis-scorer(:05) → macro-pulse(:10) | gp-monitor(06:00) | report-generator(07:00)\n")
        f.write("#\n")
        for cron_expr, entry in generate_cron_entries():
            f.write(entry + "\n")
    print(f"Crontab written to {path}")
    return path


def get_scheduled_agents():
    """Return list of agents with their schedules."""
    from definitions import AGENTS
    return [
        {"name": name, **agent}
        for name, agent in AGENTS.items()
        if "schedule" in agent
    ]


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="CometCloud Scheduler Config Generator")
    parser.add_argument("--write", action="store_true", help="Write crontab to /tmp/cometcloud_cron")
    args = parser.parse_args()

    print_crontab()

    if args.write:
        write_crontab_file()
